### ISSUE TITLE
Railway no les esta funcionando

### ISSUE THREAD

**Issue by tiagoramirez** [nachovilla123/service-01-merge-community-UTN#1]
El deploy de la aplicación tiene problemas.

Por ejemplo, este endpoint no estaria funcionando:

POST https://service-01-merge-community-utn-production.up.railway.app/api/recommendations

Saludos!

**Comment by nachovilla123** [comment]
Buenas! se nos había terminado la prueba gratuita, creo que ya lo restauramos. 
Me confirmarías? 
Saludos!

**Comment by tiagoramirez** [comment]
Funcionando.
Muchas gracias! 😊👌
